use dyncdb;
grant all privileges on `dbuser_%`.* to root@localhost identified by 'root' with grant option;
FLUSH PRIVILEGES;

ALTER TABLE `ISSUE` CHANGE `USER_ID` `USER_ID` INT(50);
ALTER TABLE `ISSUE` ADD `UPLOAD` VARCHAR(50);
ALTER TABLE `ISSUE` ADD FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `WINDOW`  ADD FOREIGN KEY (`ISSUE_ID`) REFERENCES `ISSUE` (`ISSUE_ID`);
ALTER TABLE `WINDOW`  ADD FOREIGN KEY (`CODE_ID`) REFERENCES `CODE` (`CODE_ID`);
ALTER TABLE `CODE`  ADD FOREIGN KEY (`CODE_REPOSITORY`) REFERENCES `CODE_REPOSITORY` (`CODE_REPOSITORY`);
ALTER TABLE `TAG`  ADD FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `CODE_REPOSITORY`  ADD FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `USER`  ADD FOREIGN KEY (`CODE_REPOSITORY`) REFERENCES `CODE_REPOSITORY` (`CODE_REPOSITORY`);